# This file contains the essential configs for the ingress controller helm chart

################################################################################
# Specify which application gateway the ingress controller will manage
#
appgw:
    subscriptionId: 043577d4-85e8-481d-950d-f5077ec9c066
    resourceGroup: jdsrg
    name: appgwContrIdentityed40

################################################################################
# Specify which kubernetes namespace the ingress controller will watch
# Default value is "default"
#
# kubernetes:
#   watchNamespace: default

################################################################################
# Specify the authentication with Azure Resource Manager
#
# Two authentication methods are available:
# - Option 1: AAD-Pod-Identity (https://github.com/Azure/aad-pod-identity)
# - Option 2: ServicePrincipal as a kubernetes secret
# armAuth:
#   type: servicePrincipal
#   secretName: networking-appgw-k8s-azure-service-principal
#   secretKey: ServicePrincipal.json
armAuth:
    type: aadPodIdentity
    identityResourceID: /subscriptions/043577d4-85e8-481d-950d-f5077ec9c066/resourcegroups/jdsrg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/appgwContrIdentityed40
    identityClientID:  413f8790-2051-4117-afd2-5ff95ee33448

rbac:
    enabled: false

aksClusterConfiguration:
    apiServerAddress: <aks-api-server-address>
